[project]
name = "agenticai-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.26",
    "langchain-groq>=0.3.4",
    "langgraph>=0.5.0",
    "langsmith>=0.4.4",
]
